# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=postgresql://secondbrain_user:mypSljCOA6yV09k54ffFjHaoi7mSG7KS@dpg-d5tn6qngi27c73fbs5m0-a.virginia-postgres.render.com/secondbrain_0rvv
spring.datasource.username=secondbrain_user
spring.datasource.password=mypSljCOA6yV09k54ffFjHaoi7mSG7KS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=secondbrain-secret-key-which-is-very-secure

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
